When text align is default, don't add a style attribute
ueberdosis/tiptap pull request #1251
Opened 2021-05-02 23:54 UTC by robguthrie

2021-05-06 12:56 UTC, zcuric approved these changes

2021-05-06 12:56 UTC, zcuric commented on packages/extension-text-align/src/text-align.ts
> +            },
Use `===` for comparison. You don't need `else`. 

```suggestion
            renderHTML: attributes => {
              if (attributes.textAlign === this.options.defaultAlignment) {
                return {};
              }
               
               return { style: `text-align: ${attributes.textAlign}` }
            },
```

2021-05-06 12:57 UTC, zcuric requested changes
Good idea, but please address these suggestions.

2021-05-06 20:08 UTC, robguthrie commented
thanks for the tips

2021-05-07 10:31 UTC, zcuric commented
@philippkuehn LGTM :)

2021-05-10 18:15 UTC, klaasgeldof commented
Was running into issues with TextAlign today. Even if you don't touch the align buttons, it always sets a style attribute of `text-align: left`. Then when you use the value in your HTML, for example like this:

```html
<div class="text-center">
    {{ $value }}
</div>
```

...the text is always left aligned.

This PR should fix this.

2021-05-11 15:04 UTC, merged