Convenience extension - TableKit
ueberdosis/tiptap pull request #2765
Opened 2022-05-08 00:52 UTC by drnic

Akin to StarterKit, this extension TableKit imports all extensions to form a table:

```html
        <table>
          <tbody>
            <tr>
              <th>Name</th>
              <th colspan="3">Description</th>
            </tr>
            <tr>
              <td>Cyndi Lauper</td>
              <td>singer</td>
              <td>songwriter</td>
              <td>actress</td>
            </tr>
            <tr>
              <td>Philipp Kühn</td>
              <td>designer</td>
              <td>developer</td>
              <td>maker</td>
            </tr>
            <tr>
              <td>Hans Pagel</td>
              <td>wrote this</td>
              <td colspan="2">that’s it</td>
            </tr>
          </tbody>
        </table>
```

I've confirmed that linting passes and packages can be built.

I have not added any new documentation nor used it in any demos yet.

This is my first PR. I wanted to check that you wanted this convenience extension (that I'm on the right path to making tiptap more delightful for everyone).

If you'd like me to have a crack at adding some docs/demos, or updating the docs/demos to reference this `TableKit` instead of the underlying extensions, I will do that.

2022-05-08 01:05 UTC, drnic commented
Perhaps the convenience of `TableKit` clashes with the configurability of adding each extension explicitly, such as the demos in the repo:

```js
        Table.configure({
          resizable: true,
        }),
        TableRow,
        TableHeader,
        TableCell,
```

2022-05-09 11:15 UTC, bdbch commented
Thanks for your PR, pretty nice idea.

> Perhaps the convenience of `TableKit` clashes with the configurability of adding each extension explicitly, such as the demos in the repo:
> 
> ```js
>         Table.configure({
>           resizable: true,
>         }),
>         TableRow,
>         TableHeader,
>         TableCell,
> ```

Maybe we could provide this functionality via `Tablekit.configure` which takes all options for each extension into account, but I'm not sure if this is adding to much complexity in comparision to just adding each extension on it's own.

2022-05-09 15:30 UTC, jameslesliewatts commented
> Thanks for your PR, pretty nice idea.
> 
> > Perhaps the convenience of `TableKit` clashes with the configurability of adding each extension explicitly, such as the demos in the repo:
> > ```js
> >         Table.configure({
> >           resizable: true,
> >         }),
> >         TableRow,
> >         TableHeader,
> >         TableCell,
> > ```
> 
> Maybe we could provide this functionality via `Tablekit.configure` which takes all options for each extension into account, but I'm not sure if this is adding to much complexity in comparision to just adding each extension on it's own.

Our team has implemented this locally (as well as an ImageKit) and we do something similar to that. 

More specifically, we pass a config of package names and options for `configure` into a function that parses through and instantiates the Editor instance. If it finds a name that includes `kit`, it passes the `options` of that back into the function recursively. We also allow for excluding.

2022-05-12 01:04 UTC, drnic commented
@bdbch yes, I'll bring in the ability to opt out of each individual sub-extension (like `StarterKit.configure({history: false})`) and for `Table` options to be set via `Table.configure`. Good idea.

2022-05-17 11:18 UTC, bdbch commented
Hey @drnic any update?

2022-05-18 01:36 UTC, drnic commented
Thanks for prompt.

`TableKit` is now configurable like StarterKit, and the sub-extensions are opt-outable. I've updated the Tables React/Vue demos to use `@tiptap/table-kit` with resizable: true as it was configured before:

```js
TableKit.configure({
  table: { resizable: true },
}),
```

2022-05-20 19:31 UTC, bdbch requested changes

2022-05-20 19:31 UTC, bdbch commented on demos/src/Examples/Tables/React/index.jsx
> +        tableCell: false,
Don't we need tableCells in this demo?

2022-05-20 19:31 UTC, bdbch commented on demos/src/Examples/Tables/Vue/index.vue
> +          tableCell: false,
Same here

2022-06-24 15:46 UTC, closed without merging