fix: Queue flushSync call
ueberdosis/tiptap pull request #3533
Opened 2022-12-13 06:58 UTC by kylealwyn

Do the same thing as https://github.com/ueberdosis/tiptap/pull/3188 - confirmed this got rid of the warning locally

2022-12-17 07:10 UTC, develink commented
Looks good. Can you merge ASAP?

2022-12-21 11:24 UTC, konstantinmuenster requested changes
Using `queueMicrotask` removes the warning but introduces this issue #3331 again. If we queue the update, changes are not immediately flushed to the DOM.

I think we instead need to reset the `initialized` flag properly when the editor unmounts. For us, the warning only occurred in those situations. Adding `this.initialized = false` before we reset the node views, worked for us:

```tsx
  componentWillUnmount() {
    const { editor } = this.props

    if (!editor) {
      return
    }

    this.initialized = false

    if (!editor.isDestroyed) {
      editor.view.setProps({
        nodeViews: {},
      })
    }

    editor.contentComponent = null

    if (!editor.options.element.firstChild) {
      return
    }

    const newElement = document.createElement('div')

    newElement.append(...editor.options.element.childNodes)

    editor.setOptions({
      element: newElement,
    })
  }
```

2022-12-30 04:51 UTC, diegoulloao commented
what is the status for this PR? I need this fix ASAP.
Is pending of approval?

2023-01-08 17:09 UTC, jamesopti commented
> Using queueMicrotask removes the warning but introduces this issue https://github.com/ueberdosis/tiptap/pull/3331 again. If we queue the update, changes are not immediately flushed to the DOM.

@konstantinmuenster is right. Reintroducing #3331 would be a mistake.

I will try @konstantinmuenster 's fix in our fork and report back.

2023-01-09 12:56 UTC, Aldredcz commented
Also experiencing this bug since we updated to `2.0.0-beta.209`.
It happens when editor component is unmounted.

+1 on fixing this ASAP 🙏

2023-01-11 10:40 UTC, diegoulloao commented
any news on this??

2023-01-15 10:50 UTC, JosephHalter commented
+1

2023-01-17 15:13 UTC, anton-liubushkin commented
🤔

2023-01-20 23:17 UTC, koffietiger commented
+1, project is failing build with this issue. 😅

2023-01-20 23:37 UTC, JosephHalter commented
> +1, my project is failing build with this issue. 😅

Rolling back to `2.0.0-beta.202` is the only solution right now.

2023-01-20 23:47 UTC, koffietiger commented
> > +1, my project is failing build with this issue. 😅
> 
> 
> 
> Rolling back to `2.0.0-beta.202` is the only solution right now.

I've actually rolled back all the way to 199 and still having this issue 😅

Though could be same error but unrelated issue... I'm working with NextJS.

2023-01-25 12:47 UTC, amit-verma-qatalog commented
upgraded to `2.0.0-beta.209` and i see a lot of these errors. is there any timeline for this fix, or should we revert to `202`

2023-02-13 23:32 UTC, kalda341 commented
@jamesopti, how did that fix go? Would be great to get this sorted.

2023-02-18 21:46 UTC, bdbch approved these changes

2023-02-18 21:47 UTC, merged

2023-02-25 22:50 UTC, jamesopti commented
> @jamesopti, how did that fix go? Would be great to get this sorted.

Sorry for the delay in testing this. I just got a chance to and unfortunately, the issue NodeView cursor issue remains.

Here is a codesandbox showing the issue with the latest code from @tiptap/react manually included (which has this fix)

https://codesandbox.io/s/react-nodeview-flushsync-debug-mji07b?file=/src/App.tsx

2023-02-25 22:59 UTC, jamesopti commented
Here's a codesandbox using @konstantinmuenster 's fix and it appears to work as expected: https://codesandbox.io/s/react-nodeview-flushsync-debug-alternate-thmr3m?file=/src/App.tsx

I'll test this in our app and report back.

2023-02-26 01:13 UTC, bdbch commented
Hey. I have the fix proposed by @konstantinmuenster merged into main already and will release it on monday morning. Looking forward to hear your feedback!

2023-04-01 00:18 UTC, maxenko commented
2.0.1
This bug is still there. Happens what appears to be about 70% of the time when updating custom properties.

triggered via either of the commands:
```js
addCommands() {
	return {
		setInlineImageFloat: (floatTo) => ({ commands }) => {
			return commands.updateAttributes('inline-image', {'data-float': floatTo});
		},

		setInlineImageSize: (sizeTo) => ({ commands }) => {
			return commands.updateAttributes('inline-image', {'data-size': sizeTo});
		}
	};
},
```

```
Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.
ImageComponent@webpack-internal:///./src/components/ui/kit/editor/tiptap/InlineImage/index.js:75:54
ReactNodeView
Portals@webpack-internal:///./node_modules/@tiptap/react/dist/index.js:143:17
PureEditorContent@webpack-internal:///./node_modules/@tiptap/react/dist/index.js:150:9
div
__webpack_exports__.default<@webpack-internal:///./src/components/ui/kit/editor/tiptap/tiptap-editor.js:109:75
div
main
IndexPage@webpack-internal:///./src/pages/[...].js?export=default:68:30
PageRenderer@webpack-internal:///./.cache/page-renderer.js:24:13
PageQueryStore@webpack-internal:///./.cache/query-result-store.js:35:30
RouteHandler
div
re@webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:9911
ee@webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:9706
ae@webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:11013
oe@webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:10831
ScrollHandler@webpack-internal:///./node_modules/gatsby-react-router-scroll/scroll-handler.js:23:35
RouteUpdates@webpack-internal:///./.cache/navigation.js:253:32
EnsureResources@webpack-internal:///./.cache/ensure-resources.js:19:30
LocationHandler@webpack-internal:///./.cache/root.js:62:29
G@webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:9063
Root
ye@webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:29:12744
QueryParamProviderInner@webpack-internal:///./node_modules/use-query-params/dist/QueryParamProvider.js:27:33
QueryParamProvider@webpack-internal:///./node_modules/use-query-params/dist/QueryParamProvider.js:46:28
z<@webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:8273
F@webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:7181
H@webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:7472
WithErrorBoundary()
G@webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:9063
__webpack_exports__.default@webpack-internal:///./node_modules/gatsby-plugin-use-query-params/root.js:17:7
StaticQueryStore@webpack-internal:///./.cache/query-result-store.js:130:32
SliceDataStore@webpack-internal:///./.cache/query-result-store.js:177:32
ErrorBoundary@webpack-internal:///./.cache/fast-refresh-overlay/components/error-boundary.js:21:35
DevOverlay@webpack-internal:///./.cache/fast-refresh-overlay/index.js:120:7
RootWrappedWithOverlayAndProvider
App@webpack-internal:///./.cache/app.js:167:80
```