Adds attributes to toggleList
ueberdosis/tiptap pull request #3776
Opened 2023-02-23 07:57 UTC by katerlouis

When dealing with different variants of bullet lists, I wanted to adopt the same technique I used for different paragraph variants. Since `wrapInList` is capable of receiving attributes, just like `setNode` is, I don't see any reason why `toggleList` should not be capable of the same. 

Here's my bullet list extension in action that is in need of attributes support.

```js
export const CustomBulletList = BulletList.extend({
  content: 'listItem*',

  addAttributes() {
    return {
      variant: {
        default: DEFAULT_LIST,

        renderHTML: attributes => {
          return {
            class: `list-${attributes.variant}`,
          };
        },
      },
    };
  },

  addCommands() {
    return {
      toggleBulletList: attributes => (c) => {
        return c.commands.toggleListCustom(this.name, this.options.itemTypeName, true, attributes);
      },
    };
  },
});
```

2023-03-02 13:51 UTC, bdbch requested changes
Nice, thank you. Just one minor thing.

@svenadlung you also want to review?

2023-03-02 13:51 UTC, bdbch commented on docs/api/commands/toggle-list.md
> +`attributes?: Record<string, any>
I think you're missing a trailing ` here.

2023-03-02 15:14 UTC, svenadlung reviewed
LGTM besides what @bdbch has already mentioned

2023-03-03 08:50 UTC, bdbch approved these changes

2023-03-03 08:55 UTC, bdbch commented
Could you check the linting issues again @katerlouis ?

2023-03-03 08:56 UTC, bdbch commented
Nevermind - seems to come from outside. I'll fix it!

2023-03-03 08:59 UTC, merged

2023-03-28 06:10 UTC, gethari commented
@bdbch I could'nt able to find this attribute code (`variant`) in latest default branch `develop` ? Is it missed or am I missing something ?

2023-03-28 06:51 UTC, bdbch commented
@gethari can you double check that rc.1 is installed?