Add support for custom selection builders
ueberdosis/tiptap pull request #4128
Opened 2023-06-14 08:53 UTC by benglewis

## Please describe your changes

Add support for custom selection builders.

## How did you accomplish your changes

Added new field to the extension options, type and passing along parameter to the `y-prosemirror` extension. Passing by default the existing default value to avoid breaking anything.

## How have you tested your changes

Ran the existing collaboration demo locally with the changes applied. Verified that the cursor and selection is shown correctly.

## How can we verify your changes

You can clone code and check that the collaboration cursor and selection is not broken.

## Remarks

N/A

## Checklist

- [x] The changes are not breaking the editor
- [] Added tests where possible - N/A
- [x] Followed the guidelines
- [x] Fixed linting issues

2023-06-26 07:40 UTC, benglewis commented
@bdbch Can you please take a look?

2023-07-07 13:10 UTC, bdbch requested changes
nice one! could you add the new `selectionRender` option to the docs too? @benglewis

2023-07-10 09:26 UTC, benglewis commented
@bdbch I've added the property to the documentation. Hopefully I understood how to do it correctly.

2023-07-10 16:23 UTC, RubaXa commented
@bdbch please, merge and release this request 🙇🏻‍♂️

2023-07-16 16:29 UTC, benglewis commented
@bdbch Any updates regarding this merge? 🙏

2023-08-02 07:49 UTC, benglewis commented
Hi @svenadlung  @bdbch ,

Is there any chance that you can please review and merge this PR? 🙏 
We are getting to the stage where we may need to patch TipTap for the meantime with this fix for our use-case and I'd prefer for us not to have to patch it

2023-08-03 08:23 UTC, bdbch approved these changes

2023-08-03 08:30 UTC, merged