[Bug]: HTML output of Table is missing colgroup element
ueberdosis/tiptap pull request #4281
Opened 2023-08-02 19:10 UTC by diginikkari

Fixes #4280

## Please describe your changes

Added createColGroup function to generate colGroup based on child nodes (imitates `updateColumns` which is used for editor TableView.

## How did you accomplish your changes

`renderHTML` is calling `updateColumns` to get generated `colgroup` element, `tableWidth` and `tableMinWidth` values.

## How have you tested your changes

Updated *react* and *vue* e2e tests to assert that there is `colgroup` -element.

## How can we verify your changes

[add a detailed description of how we can verify your changes here]

## Remarks

[add any additional remarks here]

## Checklist

- [x] The changes are not breaking the editor
- [x] Added tests where possible
- [x] Followed the guidelines
- [x] Fixed linting issues

## Related issues

#721

2023-08-04 23:35 UTC, bdbch requested changes

2023-08-04 23:35 UTC, bdbch commented on packages/extension-table/src/utilities/createColGroup.ts
> +  const colls: DOMOutputSpec[] = []
Typo: `colls` => `cols`

2023-08-11 03:46 UTC, bdbch approved these changes

2023-09-30 07:53 UTC, diginikkari commented
@bdbch any change to get this merged any time soon?

2023-10-10 02:22 UTC, merged

2023-11-28 01:29 UTC, iowxy commented on packages/extension-table/src/table.ts
> +          : `minWidth: ${tableMinWidth}`,
minWidth or `min-width` ?