Fix: Upgrade lowlight to 3.1.0 and update demo (CodeBlockLowlight)
ueberdosis/tiptap pull request #4588
Opened 2023-10-31 09:35 UTC by RakeshPotnuru

## Please describe your changes

- Upgraded `lowlight` to `3.1.0`
- Updated demo for React `CodeBlockLowlight` Node.

## How did you accomplish your changes

By reading lowlight docs.

## How have you tested your changes

Yes, tested locally in my project.

## How can we verify your changes

Read lowlight v3 [Changelog](https://github.com/wooorm/lowlight/releases/tag/3.0.0).

## Remarks

-

## Checklist

- [x] The changes are not breaking the editor
- [x] Added tests where possible
- [x] Followed the guidelines
- [x] Fixed linting issues

## Related issues

#4456

2024-04-05 23:40 UTC, bdbch commented
@RakeshPotnuru sorry for coming back so late to this. Could you reoslve the merge conflicts and rerun the tests via your commit so we can get this merged?

2024-04-06 06:27 UTC, RakeshPotnuru commented
@bdbch, it looks like conflicts are resolved.

2024-04-06 09:41 UTC, bdbch requested changes
@RakeshPotnuru could you take a look at the changes in the collaboration extension? seems like they were changed unpurposely?

2024-04-06 09:41 UTC, bdbch commented on packages/extension-collaboration/src/collaboration.ts
> +type YSyncOpts = Parameters<typeof ySyncPlugin>[1]
Do you know where the changes on this file come from? Seems like they are unrelated to your changes, right?

2024-04-06 10:10 UTC, RakeshPotnuru commented
@bdbch  I thing it's because multiple PRs got merged into `develop` branch from their respective forks. Should I create a new PR?

<img width="911" alt="image" src="https://github.com/ueberdosis/tiptap/assets/70439799/eb451a6f-da75-4954-a21a-642ff221fdbf">

2024-04-06 11:01 UTC, bdbch commented
Yep I think you'd need to rebase your PR to main and keep out the changes from develop.

2024-04-06 11:17 UTC, RakeshPotnuru commented
#5036

2024-04-06 11:17 UTC, closed without merging