fix (mention/heading): clashing heading markdown command and mention/suggestion with #
ueberdosis/tiptap pull request #4954
Opened 2024-03-07 02:26 UTC by VV-EE

## Please describe your changes

Fixes https://github.com/ueberdosis/tiptap/issues/2570
Now mention nodes with # will preempt the heading markdown input rule

## How did you accomplish your changes

Instead of using `addInputRules` I've added the heading input rule as a separate ProseMirror plugin. After this higher priority extensions will be ahead of this input rule. For the same reason I set the Mention node's priority to 101.

## How have you tested your changes

Added two E2E tests, one checks if there's no heading created is something is selected from the mention list the other checks that we can still use the heading shortcut if we don't select anything.

## How can we verify your changes

Run the E2E test, or visit `preview/Examples/HeadingWIthMention`

## Remarks

Added some documentation to Mention about higher priority.

## Checklist

- [ x] The changes are not breaking the editor
- [ x] Added tests where possible
- [ x] Followed the guidelines
- [ x] Fixed linting issues

2024-04-03 11:02 UTC, svenadlung requested changes
Pretty cool! Thank you so much 🙌

2024-04-03 11:03 UTC, svenadlung commented
@bdbch what do you think? What do you think of this solution?

2024-04-03 14:13 UTC, svenadlung commented
@VV-EE we are still in internal discussion to find a better way to respect the priority of the input rules in the ExtensionManager.

2024-04-04 01:38 UTC, VV-EE commented on packages/extension-mention/src/mention.ts
> +  priority: 101, // Fixes collision with Heading '#' input rule
I've put the comment on a separate line, I hope that's what you meant.

2024-04-04 01:46 UTC, VV-EE commented
I get it, this is a workaround, not a solution to the underlying problem. I thought about adding an extra `forcePriority` prop to `ExtensionManager` and order all plugins with that too, but I don't know how often this problem happens. If it's a one-off then a workaround is better IMO.

2026-05-13 14:12 UTC, bdbch commented
Hey, sorry for the late turn-around. I think this PR is not needed anymore as we introduced an extension-priority based system [here](https://github.com/ueberdosis/tiptap/pull/6832). If you think it's still valid, feel free to reopen! Thanks.

2026-05-13 14:12 UTC, closed without merging