Fix XSS potential
ueberdosis/tiptap pull request #5157
Opened 2024-05-15 21:24 UTC by Nantris

## Changes Overview
Fix XSS potential

## Implementation Approach
Trim and lowercase href before comparing. Rely on getAttrs instead of CSS selector.

## Testing Done
None

## Verification Steps

## Additional Notes
**Given that this potential was already overlooked, it's essential that these changes be tested and examined more vigorously by the core team than they were in the past.**

## Checklist
- [ ] I have renamed my PR according to the naming conventions. (e.g. `feat: Implement new feature` or `chore(deps): Update dependencies`)
- [ ] My changes do not break the library.
- [ ] I have added tests where applicable.
- [x] I have followed the project guidelines.
- [ ] I have fixed any lint issues.

## Related Issues
#3673

2024-05-15 21:38 UTC, Nantris commented
Demo of fixes: https://codesandbox.io/p/sandbox/cool-field-2sg2pl?file=%2Fsrc%2FApp.js%3A74%2C17

2024-05-15 21:41 UTC, Nantris commented
@svenadlung @bdbch it's paramount that these changes be integrated as quickly as feasible to resolve XSS potential.

There's one linting issue I'm not really sure what to do with; so I leave it to you. I didn't see any way to prevent parsing `  
 javascript:` hrefs (note leading spaces) in the `parseHTML` without abandoning the CSS-selector approach. We could filter for `javascript:` anywhere in the href but I'm not certain that won't exclude potentially valid hrefs.

2024-05-16 00:29 UTC, Nantris commented
Not sure what mistake I've made in this PR that has it failing. Can anyone advise? Despite the high priority of this issue, our editor isn't even ready to ship, so I won't have much more time to work on this issue.

2024-05-16 06:08 UTC, bdbch commented
@Nantris happy to get his merged and released ASAP. The test failing is because the `dom` on getAttr can be a string OR dom element so `.getAttribute` is not working on a string.

I think you'd need to do a typecheck beforehand.

2024-05-16 06:09 UTC, bdbch requested changes

2024-05-16 06:09 UTC, bdbch commented on packages/extension-link/src/link.ts
> +        const href = dom.getAttribute('href')
I think here we need a typecheck as dom apparently can also be a string (at least typescript says so) so you can't get the href directly from a string object as `getAttribute` does not exist

2024-05-16 17:57 UTC, nperez0111 commented
We resolved this with https://github.com/ueberdosis/tiptap/pull/5160

2024-05-16 17:57 UTC, closed without merging

2024-05-16 17:58 UTC, nperez0111 commented
But we appreciate your contribution, your work was helpful in the final fix.

We did this a bit strangely because of the multiple PRs and the urgency of it

2024-05-16 22:05 UTC, Nantris commented
Glad it's taken care of! Thanks for the quick action and words of appreciation.