Fixed issue where can() returned false when the command was executable
ueberdosis/tiptap pull request #5744
Opened 2024-10-21 04:00 UTC by guanriyue

## Changes Overview

Fix the issue where can() check returns false even when the command is actually executable. And added cypress test cases.

## Implementation Approach

When chainCommand is executed, multiple commands are run sequentially. The editor state used by later commands may depend on the preceding commands. Therefore, when executing can(), createChain must ensure that shouldDispatch is true to prevent skipping operations on tr.

This fix effectively reverts the code changes from the pull request https://github.com/ueberdosis/tiptap/pull/3026 and resolves the issue https://github.com/ueberdosis/tiptap/issues/3025 caused by the clearNodes error.

At the same time, it will also fix issue https://github.com/ueberdosis/tiptap/issues/3229 and issue https://github.com/ueberdosis/tiptap/issues/4057.

For more details, please refer to this issue https://github.com/ueberdosis/tiptap/issues/5721.

## Testing Done

First, add the disabled attribute to the heading and list action buttons in the example default editor.

Before the fix, if the selection was on a heading node, the list action buttons would remain disabled, even though the commands were actually available. After the change, the list action buttons will appear enabled.

Additionally, corresponding Cypress test cases have been added.

## Verification Steps

Access the default example editor at https://tiptap.dev/docs/examples/basics/default-text-editor or by executing cypress test

## Additional Notes

## Checklist
- [ ] I have created a [changeset](https://github.com/changesets/changesets) for this PR if necessary.
- [x] My changes do not break the library.
- [x] I have added tests where applicable.
- [x] I have followed the project guidelines.
- [x] I have fixed any lint issues.

## Related Issues

- https://github.com/ueberdosis/tiptap/issues/5721
- https://github.com/ueberdosis/tiptap/issues/3229
- https://github.com/ueberdosis/tiptap/issues/4057
- https://github.com/ueberdosis/tiptap/issues/3025

2024-10-25 17:55 UTC, nperez0111 commented
Hey @guanriyue I haven't reviewed this super thoroughly, because I think that this approach is wrong.

What `can` is meant for is to be able to allow commands to check whether they would be able to execute without actually modifying the document via transactions. At times, this can be sort of ambiguous, so sometimes a lazy implementation may not actually implement this properly. I think that `clearNodes` in this case is just implemented improperly where it should not have that early dispatch.

I do not believe that you need to actually change `can` in this case. I think that what needs to happen is there needs to be a better implementation of `clearNodes`.

2024-10-25 17:58 UTC, nperez0111 requested changes

2024-10-25 17:58 UTC, nperez0111 commented on packages/core/src/CommandManager.ts
> +    const dispatch = true
I believe this is wrong.

If dispatch is true, commands will think that they can modify the `transaction` when they should not be able to.

`dispatch` should probably be named `shouldDispatch` where it being `false` means you should not, as a command, actually apply your change to the editor.

2024-10-25 17:58 UTC, nperez0111 commented on tests/cypress/integration/core/can.spec.ts
This test was correct. Please revert

2024-10-25 17:58 UTC, nperez0111 commented on packages/core/src/commands/clearNodes.ts
The actual problem in this file is:
```ts
  if (!dispatch) {
    return true
  }
```

2024-10-28 09:52 UTC, guanriyue commented
Have you looked at the description of this issue https://github.com/ueberdosis/tiptap/issues/5721? I explained why I believe `dispatch` should be a function in `can.chain`.

Perhaps it is a mistake; in fact, setting `dispatch` to true was part of the code logic before the last bug fix https://github.com/ueberdosis/tiptap/pull/3026. It's actually a bit of a long story.

Four years ago, at the very beginning, the `dispatch` variable was set to `false`.
https://github.com/ueberdosis/tiptap/commit/7bfab4685f958be82a3519c6cbd377977c88794d#diff-ac93a7861b6cdca5f5dd83ec422e904ebb145fd00a39343834384c6d241965c6R103

About five months later, it was changed to `undefined` for unclear reasons. When passed into `buildProps`, JavaScript treated it as true by default. These two changes come from the same author.
https://github.com/ueberdosis/tiptap/commit/ca8d1a42450be9d41adf64697b607c3ca8697f4f#diff-ac93a7861b6cdca5f5dd83ec422e904ebb145fd00a39343834384c6d241965c6L87-R90

About a year and a half later, `clearNodes` caused an error, but the issue with `clearNodes` was not fixed, and executing `command.clearNodes` could still lead to problems, while the implementation of `createCan` was modified. `dispatch` was reset to `false`.
https://github.com/ueberdosis/tiptap/commit/40f4ea31efc59c1578b783a5b64572ac2846c5a6#diff-ac93a7861b6cdca5f5dd83ec422e904ebb145fd00a39343834384c6d241965c6L109-R111

After that fix, several new issues with can checks emerged.
- https://github.com/ueberdosis/tiptap/issues/3229
- https://github.com/ueberdosis/tiptap/issues/4057

I am now trying to change it back to `true` .  And fix the real issue in `clearNodes`. It runs all the tests successfully on my local machine, except for the `can.chain.dispatch.except.to.be.undefined`, which is a test case added after the fix https://github.com/ueberdosis/tiptap/pull/3026.

> If dispatch is true, commands will think that they can modify the transaction when they should not be able to.

Yes, you're right. However, in `can.chain`, it seems that we should not skip modifications on `tr` under any circumstances, as subsequent commands may depend on the state and `tr` after the preceding command is executed. Just like how skipping `clearNodes` caused issues. There are many commands similar to `clearNodes`. In our pursuit of higher performance and avoiding unnecessary code execution, we tend to favor lazy implementations.

> dispatch should probably be named shouldDispatch where it being false means you should not, as a command, actually apply your change to the editor.

Yes, that is an inappropriate naming; it should be renamed to `shouldDispatch`.

2024-10-28 09:55 UTC, guanriyue commented on packages/core/src/commands/clearNodes.ts
Remove this section of code will resolve the current issue. However, it seems there is a deeper problem that needs to be addressed, which would involve a significant change.

I will take your advice and work to close this PR as soon as possible.

2024-11-04 09:55 UTC, nperez0111 commented
I'm sorry, but, I still believe that this is all misguided. Please refer to the documentation of Prosemirror https://prosemirror.net/docs/guide/#commands It specifically says that:

> To figure out whether a selection can currently be deleted, you'd call deleteSelection(view.state, null), whereas to actually execute the command, you'd do something like deleteSelection(view.state, view.dispatch). A menu bar could use this to determine which menu items to gray out.

> In this form, commands do not get access to the actual editor view—most commands don't need that, and in this way they can be applied and tested in settings that don't have a view available. But some commands do need to interact with the DOM—they might need to [query](https://prosemirror.net/docs/ref/#view.EditorView.endOfTextblock) whether a given position is at the end of a textblock, or want to open a dialog positioned relative to the view. For this purpose, most plugins that call commands will give them a third argument, which is the whole view.

> function blinkView(_state, dispatch, view) {
>  if (dispatch) {
>    view.dom.style.background = "yellow"
>    setTimeout(() => view.dom.style.background = "", 1000)
>  }
>  return true
> }
> That (rather useless) example shows that commands don't have to dispatch a transaction—they are called for their side effect, which is usually to dispatch a transaction, but may also be something else, such as popping up a dialog.

It specifically says it should be called like `deleteSelection(view.state, null)`, with the implementation as:

```js
 function blinkView(_state, dispatch, view) {
  if (dispatch) {
    view.dom.style.background = "yellow"
    setTimeout(() => view.dom.style.background = "", 1000)
  }
  return true
 }
```

This is done purposefully, so that a command can be "tried" without actually committing the side-effect. If you pass `true` you defeat the purpose of it as you'll modify the editor content with the transaction or side-effect.


You are not solving the real problem which is the implementation of the command. You are attempting to change how can chains work to fit a wrong implementation, fix the implementation not how can chains work.

2024-11-04 09:57 UTC, nperez0111 commented on packages/core/src/commands/clearNodes.ts
This is what the PR should be addressing. Everything else around this PR is incorrect with the intention behind can chains and how they should work

2025-07-19 15:25 UTC, closed without merging